import type { Metadata } from "next";
import { Inter, Geist } from "next/font/google";
import "@/styles/globals.scss";
import "@/styles/globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Organisms/Navbar/Navbar";
import Footer from "@/components/Organisms/Footer/Footer";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full antialiased", "font-sans", geist.variable)}
    >
      <body className={inter.className} suppressHydrationWarning>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
